import Foundation

extension Strings {
    static func english(_ key: LKey) -> String {
        switch key {
        case .tabHome: "Home"
        case .tabActivity: "Activity"

        // Offline maps
        case .offlineMaps: "Offline maps"
        case .offlineMapsBody: "Save an area before you travel. Download once on Wi-Fi, then browse its streets and buildings without mobile data."
        case .offlineWiFiOnly: "Download on Wi-Fi only"
        case .offlineDownloadedOnly: "Use downloaded maps only"
        case .offlineOnlyBody: "Stops all Mapbox map downloads. Unsaved areas may appear blank. Turn off to download or update an area."
        case .offlineSlipway: "Slipway & waterfront"
        case .offlineSlipwayDetail: "A 2 km coastal area around Slipway"
        case .offlinePeninsula: "Msasani peninsula"
        case .offlinePeninsulaDetail: "Masaki, Oyster Bay and Msasani · about 7 km across"
        case .offlineCentral: "Central Dar es Salaam"
        case .offlineCentralDetail: "City centre, Upanga, Kariakoo and nearby districts · about 13 km across"
        case .offlineDownload: "Download area"
        case .offlineUpdate: "Update"
        case .offlineReady: "Available offline"
        case .offlinePreparing: "Saving map style…"
        case .offlineDownloading: "Saving streets and buildings…"
        case .offlinePaused: "Paused — downloaded resources are kept"
        case .offlineResume: "Resume download"
        case .offlineFailed: "Download incomplete. Check your connection and free storage, then retry. Large areas may reach the map provider’s offline limit."
        case .offlineRemoveFailed: "Couldn’t remove this area. Please retry."
        case .offlineRemoveTitle: "Remove downloaded area?"
        case .offlineRemoveBody: "This removes its offline availability. Shared map resources may remain cached for other areas."
        case .offlineInventoryFailed: "Couldn’t read downloaded areas. Please retry."
        case .offlineDisableOnly: "Turn off “Use downloaded maps only” to download."
        case .offlineConnect: "Connect to the internet to download an area."
        case .offlineNeedWiFi: "Connect to Wi-Fi without Low Data Mode to download, or turn off Wi-Fi only."
        case .offlineLimitations: "Maps include street-level detail through zoom 16. Closer views use that saved detail. Keep Zuri open while downloading; leaving the app pauses the download. Search, live rides, directions and payments still need internet. Sizes report stored map resources, which can be shared between areas."
        case .offlineBundled: "Slipway’s custom 3D buildings and scenery are already included in Zuri. No separate model downloads are needed."
        case .offlinePartial: "Incomplete area"
        case .offlineProgress: "%d%% · %@ saved"

        // Common
        case .back: "Back"
        case .close: "Close"
        case .cancel: "Cancel"
        case .continueAction: "Continue"
        case .skip: "Skip"
        case .change: "Change"
        case .remove: "Remove"
        case .delete: "Delete"
        case .clear: "Clear"
        case .gotIt: "Got it"
        case .verify: "Verify"
        case .copy: "Copy"
        case .copied: "Copied"
        case .seeAll: "See all"
        case .saved: "Saved"
        case .saveChanges: "Save changes"
        case .menu: "Menu"
        case .recentre: "Recentre map"
        case .birdsEye: "Bird’s-eye view"
        case .birdsEyeHint: "Look straight down without changing your location or zoom. Use two fingers to tilt the map again."
        case .request: "Request"
        case .notNow: "Not now"
        case .tryAgain: "Try again"
        case .backToHome: "Back to home"
        case .minutesShort: "%ld min"
        case .minuteUnit: "min"
        case .yourLocation: "Your location"
        case .recommended: "Recommended"
        case .darEsSalaam: "Dar es Salaam"
        case .madeInDar: "Made in Dar es Salaam"
        case .nearPlace: "Near %@"
        case .droppedPin: "Dropped pin"

        // Splash & language
        case .splashTagline: "Zero-commission rides in Dar"
        case .splashFooter: "Drivers keep 100% of every fare"
        case .languageTitle: "Choose your language"
        case .languageSubtitle: "You can change this any time in Settings."

        // Phone & OTP
        case .phoneTitle: "What's your number?"
        case .phoneSubtitle: "We'll text you a 6-digit code to sign in."
        case .phoneLabel: "Phone number"
        case .phoneHint: "Tanzanian mobile numbers only (06 / 07)."
        case .sendCode: "Send code"
        case .otpTitle: "Enter the code"
        case .otpSubtitle: "Sent by SMS to %@"
        case .otpResendIn: "Resend code in %@"
        case .otpResend: "Resend code"
        case .otpChangeNumber: "Change number"
        case .otpInvalid: "That code didn't match. Try again."
        case .otpDemoHint: "Demo: any 6 digits work."

        // Profile setup
        case .profileTitle: "Tell us your name"
        case .profileSubtitle: "Drivers see your first name when they accept your ride."
        case .fullName: "Full name"
        case .fullNamePlaceholder: "e.g. Asha Mohamed"
        case .emailOptional: "Email (optional)"
        case .profilePrivacy: "Your number is never shown to drivers. Calls are connected through Zuri."

        // Permission primers
        case .locationTitle: "Allow location"
        case .locationSubtitle: "So we can set your pickup and show nearby drivers."
        case .locationBullet1: "Accurate pickup without typing your address"
        case .locationBullet2: "Real arrival times from drivers near you"
        case .locationBullet3: "Only while you use the app"
        case .allowLocation: "Allow location"
        case .locationDeniedHint: "Location is off. You can still set your pickup on the map, or enable it in Settings."
        case .notificationsTitle: "Stay in the loop"
        case .notificationsSubtitle: "We'll only notify you about your rides."
        case .notificationsBullet1: "When a driver accepts and arrives"
        case .notificationsBullet2: "When a favourite driver comes online"
        case .notificationsBullet3: "Payment confirmations and receipts"
        case .allowNotifications: "Allow notifications"

        // Home
        case .goodMorning: "Good morning"
        case .goodAfternoon: "Good afternoon"
        case .goodEvening: "Good evening"
        case .whereTo: "Where to?"
        case .searchDestinationHint: "Search for a destination"
        case .favouritesOnline: "%ld online"
        case .demoLocation: "Demo pickup"
        case .addHome: "Add home"
        case .addWork: "Add work"
        case .myDrivers: "My drivers"
        case .noFavouritesTitle: "No favourite drivers yet"
        case .noFavouritesBody: "Rate a driver 5 stars to add them here."
        case .recent: "Recent"
        case .noRecents: "Your recent destinations will appear here."
        case .offlineBanner: "You're offline"
        case .serviceRide: "Ride"
        case .serviceBajaji: "Bajaji"
        case .serviceBoda: "Boda"
        case .letsGo: "Let's go"
        case .driversNearbyCount: "%ld drivers nearby"

        // Search
        case .pickupLabel: "Pickup"
        case .popularPlaces: "Popular in Dar"
        case .setOnMap: "Set location on map"
        case .stopLabel: "Stop %ld"
        case .addStop: "Add stop"
        case .addAnotherStop: "Add another stop"
        case .stopsCount: "%ld stops"
        case .removeStop: "Remove stop"
        case .reorderRoute: "Reorder route"
        case .reorderRouteHint: "Drag any place, including your pickup and destination, to change the order."
        case .moveEarlier: "Move earlier"
        case .moveLater: "Move later"
        case .whereToNext: "Where next?"
        case .setStopTitle: "Set stop"
        case .confirmStopHere: "Add stop here"
        case .chooseDestination: "Choose destination"
        case .maxStopsReached: "You can add up to %ld stops"
        case .viaStops: "via %ld stops"
        case .viaOneStop: "via 1 stop"
        case .searchingPlaces: "Searching…"
        case .noResultsTitle: "No places found"
        case .noResultsBody: "Try a landmark, street or area name — or set it on the map."
        case .requestingDriver: "Requesting %@"
        case .chooseDestinationFirst: "Choose where you're going first."

        // Set on map & confirm pickup
        case .setPickupTitle: "Set your pickup"
        case .setDestinationTitle: "Set your destination"
        case .confirmPickupHere: "Pick me up here"
        case .confirmDestinationHere: "Go here"
        case .outOfZoneShort: "Outside the Dar es Salaam service area"
        case .confirmPickupTitle: "Confirm your pickup"
        case .pickupNotePlaceholder: "Note for driver, e.g. gate 2, blue building"
        case .confirmPickup: "Confirm pickup"

        // Ride options
        case .chooseRide: "Choose a ride"
        case .fareDetails: "Details"
        case .pickupInMinutes: "Pickup in %ld mins"
        case .pickupInOneMinute: "Pickup in 1 min"
        case .dropoffAtTime: "Drop-off at %@"
        case .pickupUnavailable: "No pickups nearby"
        case .dropoffUnavailable: "Drop-off time unavailable"
        case .expandRideOptions: "More ride options"
        case .collapseRideOptions: "Collapse ride options"
        case .fewDriversNearby: "Few drivers nearby"
        case .promoCode: "Promo code"
        case .willAskDriverFirst: "We'll ask %@ first, then other drivers if needed."
        case .requestDriver: "Request %@"
        case .requestRide: "Request ride"
        case .requestTier: "Request %@"
        case .tierEconomy: "Economy"
        case .tierComfort: "Comfort"
        case .tierPremium: "Premium"
        case .tierBajaji: "Bajaji"
        case .tierBoda: "Boda"
        case .tierEconomyDescription: "Everyday hatchbacks, affordable fares"
        case .tierComfortDescription: "Comfortable sedans, a smoother ride"
        case .tierPremiumDescription: "Luxury minivans, room for six"
        case .tierBajajiDescription: "Three-wheeler, quick in traffic"
        case .tierBodaDescription: "Motorbike, fastest for one"

        // Zero commission
        case .badgeDriverReceives100: "Driver receives 100% of the fare"
        case .badgeDriverReceivesAmount: "Driver receives %@ · 100%%"
        case .badgeDriverReceived: "Driver received %@ · 100%%"
        case .zeroCommissionTitle: "Zero commission"
        case .zeroCommissionBody: "Zuri doesn't take a cut of your fare. Every shilling you pay goes to the driver — which is why drivers accept faster and cancel less."
        case .zeroCommissionPoint1Title: "Drivers keep everything"
        case .zeroCommissionPoint1Body: "No 20–25% platform cut. The fare you see is the fare they keep."
        case .zeroCommissionPoint2Title: "LATRA-guided fares"
        case .zeroCommissionPoint2Body: "Prices follow the regulator's bands — no surge surprises."
        case .zeroCommissionPoint3Title: "Better drivers stay"
        case .zeroCommissionPoint3Body: "Fair pay keeps the best drivers on Zuri, and lets you pick your favourites."
        case .exampleFare: "Example: you pay → driver gets"

        // Fare breakdown
        case .fareBreakdownTitle: "Fare breakdown"
        case .baseFare: "Base fare"
        case .distanceFare: "Distance (%@)"
        case .timeFare: "Time (%ld min)"
        case .promoDiscount: "Promo discount"
        case .tip: "Tip"
        case .total: "Total"
        case .fareBreakdownNote: "Fares are fixed at booking within LATRA bands. Waiting more than 5 minutes at pickup may add TZS 100/min."

        // Payment
        case .payWith: "Pay with"
        case .cashDetail: "Pay the driver directly"
        case .addMobileMoney: "Add mobile money"
        case .payment: "Payment"
        case .payments: "Payments"
        case .defaultMethod: "Default method"
        case .unlink: "Unlink"
        case .paymentsNote: "Cash is always available. Mobile money is charged only after your trip ends, and the driver still receives 100%."
        case .linkWallet: "Link %@"
        case .useAccountPhone: "Use my Zuri number (%@)"
        case .walletNumber: "Wallet number"
        case .linkWalletNote: "You'll approve each payment with your PIN on your phone. Zuri never sees your PIN."
        case .linkAction: "Link account"

        // Zuri wallet
        case .wallet: "Zuri Wallet"
        case .walletBalance: "Balance"
        case .walletBalanceDetail: "Balance %@"
        case .walletEmptyDetail: "Top up to pay instantly"
        case .walletInsufficient: "Balance too low · %@"
        case .topUp: "Top up"
        case .topUpWallet: "Top up wallet"
        case .topUpAmount: "Amount"
        case .topUpCustomAmount: "Other amount"
        case .topUpFrom: "Pay from"
        case .topUpNoRails: "Link a mobile money account to fund your wallet."
        case .topUpLinkRail: "Link mobile money"
        case .topUpConfirm: "Add %@"
        case .topUpDone: "%@ added to your wallet"
        case .topUpMinimum: "Minimum top-up is %@."
        case .topUpMaximum: "Maximum top-up right now is %@."
        case .walletHistory: "Activity"
        case .walletNoHistory: "Top-ups and ride payments will appear here."
        case .walletTopUpTitle: "Top-up from %@"
        case .walletRidePayment: "Ride to %@"
        case .walletRefund: "Refund"
        case .walletExplainer: "Prepaid balance held by Zuri. Rides are settled instantly when they end, and the driver still receives 100%."
        case .walletPaid: "Paid from wallet"
        case .walletShortBody: "Your wallet has %@. Top up or choose another way to pay."
        case .walletShortTopUp: "Top up wallet"
        case .payWithWallet: "Pay %@ from wallet"
        case .walletAfterRide: "Charged instantly after the ride"

        // Promo codes
        case .enterCode: "Enter code"
        case .applyCode: "Apply code"
        case .promoHint: "Try KARIBU for 20% off your first ride."
        case .promoInvalid: "That code isn't valid or has already been used."
        case .promoKaribuTitle: "20% off your first ride"
        case .promoKaribuDetail: "Up to TZS 3,000. Any ride type."
        case .promoTwende10Title: "10% off this month"
        case .promoTwende10Detail: "Up to TZS 2,000. One use."

        // Out of zone
        case .outOfZoneTitle: "Not in Dar yet"
        case .outOfZoneBody: "Zuri currently serves Dar es Salaam only. %@ is outside our zone — we'll tell you when we get there."
        case .notifyMeZone: "Notify me when you launch there"
        case .notifyMeZoneConfirmed: "We'll let you know when Zuri reaches %@."
        case .notifyMeZoneAlready: "You'll be notified when we launch there"
        case .chooseAnotherPlace: "Choose another place"

        // Quick request
        case .awayFromYou: "Away"
        case .pickupEta: "Pickup ETA"
        case .viewProfile: "View profile"

        // Searching / no drivers
        case .askingDriver: "Asking %@…"
        case .findingDriver: "Finding your %@ driver…"
        case .usuallyUnder: "usually under a minute"
        case .cancelRequest: "Cancel request"
        case .noDriversTitle: "No drivers available"
        case .noDriversBody: "No %@ driver accepted nearby. Try again, or pick another ride type."
        case .tryAnotherRide: "Try another ride"
        case .notifyWhenDrivers: "Notify me when drivers are available"

        // Driver en route / arrived
        case .driverOnTheWay: "%@ is on the way"
        case .driverArrivedTitle: "%@ has arrived"
        case .meetAtPickup: "Meet at %@"
        case .arrivingIn: "Arriving in %ld min"
        case .hereNow: "Here now"
        case .call: "Call"
        case .message: "Message"
        case .favourite: "Favourite"
        case .addFavourite: "Add favourite"
        case .cancelRide: "Cancel ride"
        case .plateNumber: "Plate number"
        case .shareTrip: "Share trip"
        case .sos: "SOS"
        case .shareTripMessage: "I'm riding with %@ (plate %@) to %@ on Zuri. Follow my trip: %@"
        case .ridePINTitle: "Your ride PIN"
        case .ridePINBody: "Tell %@ this code before you get in. The ride only starts once it's entered."
        case .ridePINArrivedBody: "Check the plate, then read this code to %@ to start the ride."
        case .ridePINAccessibility: "Ride PIN %@"

        // In trip
        case .headingTo: "Heading to %@"
        case .inTraffic: "In traffic"
        case .movingWell: "Moving well"
        case .trafficMinutes: "%ld min in traffic"
        case .remaining: "remaining"
        case .fareLabel: "Fare"
        case .changeDestination: "Change destination"
        case .changeDestinationNote: "The fare will be re-quoted for the new route. Your driver is told immediately."
        case .destinationChanged: "Destination changed to %@"

        // Cancellation
        case .cancelReasonTitle: "Why are you cancelling?"
        case .cancelReasonBody: "This helps us keep drivers accountable."
        case .cancelWaitTooLong: "Waiting too long"
        case .cancelDriverNotMoving: "Driver isn't moving"
        case .cancelWrongPickup: "Wrong pickup location"
        case .cancelChangedPlans: "My plans changed"
        case .cancelDriverAsked: "Driver asked me to cancel"
        case .cancelOther: "Other"
        case .cancellationFeeNotice: "A %@ cancellation fee applies because the driver is already on the way."
        case .driverAskedNotice: "No fee. We'll follow up with the driver."
        case .cancelWithFee: "Cancel (%@ fee)"
        case .confirmCancel: "Confirm cancellation"
        case .keepRide: "Keep my ride"
        case .cancelledWithFee: "Ride cancelled. %@ fee added to your next trip."
        case .cancelledNoFee: "Ride cancelled. No fee charged."
        case .cancelledLabel: "Cancelled"
        case .cancellationReason: "Reason"
        case .cancellationFee: "Cancellation fee"

        // SOS
        case .sosTitle: "Emergency"
        case .sosBody: "Choose who to reach. Your trip details are ready to share."
        case .sosCallPolice: "Call police (112)"
        case .sosConfirmCall: "Call 112 now? Use only in a real emergency."
        case .sosCallNow: "Yes, call 112"
        case .sosAlertContacts: "Alert emergency contacts (%ld)"
        case .sosContactsAlerted: "Contacts alerted with your live trip"
        case .addEmergencyContacts: "Add emergency contacts"

        // Completion & payment
        case .tripCompleteTitle: "You've arrived"
        case .addTip: "Add a tip"
        case .noTip: "No tip"
        case .tipNote: "100% of the tip goes to the driver."
        case .payDriverInCash: "Pay the driver in cash"
        case .tapToPay: "Tap below to pay"
        case .paymentPendingBody: "Approve the prompt on your phone"
        case .paymentConfirmed: "Payment confirmed"
        case .paymentFailed: "Payment failed"
        case .paymentFailedBody: "The payment didn't go through. Retry, or pay the driver in cash instead."
        case .confirmCashPaid: "I've paid %@ in cash"
        case .retryPayment: "Retry payment"
        case .payWithMethod: "Pay with %@"
        case .payCashInstead: "Pay cash instead"
        case .waitingForConfirmation: "Waiting for confirmation…"

        // Rating
        case .rateDriver: "How was your ride with %@?"
        case .rateTrip: "How was your ride?"
        case .whatWentWrong: "What went wrong?"
        case .ratingReasonRoute: "Route"
        case .ratingReasonDriving: "Driving"
        case .ratingReasonVehicle: "Vehicle"
        case .ratingReasonBehaviour: "Behaviour"
        case .ratingReasonLate: "Late"
        case .ratingReasonPrice: "Price"
        case .addToMyDrivers: "Add %@ to my drivers"
        case .addToMyDriversShort: "Add to my drivers"
        case .submitRating: "Submit rating"
        case .thanksForRating: "Thanks! Your rating helps other riders."

        // History & receipt
        case .tripHistory: "Trip history"
        case .tripHistorySubtitle: "Receipts and past rides"
        case .noTripsTitle: "No trips yet"
        case .noTripsBody: "Your rides and receipts will appear here."
        case .receipt: "Receipt"
        case .dropoffLabel: "Drop-off"
        case .latraNotice: "Electronic receipt issued under LATRA e-hailing regulations. Keep for your records."
        case .shareReceipt: "Share PDF receipt"
        case .prepareReceipt: "Prepare PDF receipt"
        case .rebook: "Book again"
        case .reportIssue: "Report an issue"

        // Menu
        case .profile: "Profile"
        case .myDriversSubtitle: "Favourites and direct requests"
        case .onlineCount: "%ld online"
        case .savedPlaces: "Saved places"
        case .savedPlacesSubtitle: "Home, work and more"
        case .promotions: "Promotions"
        case .promotionsSubtitle: "Codes and referrals"
        case .safetyCentre: "Safety centre"
        case .safetySubtitle: "Emergency contacts and SOS"
        case .support: "Help & support"
        case .supportSubtitle: "FAQ, WhatsApp, call"
        case .settings: "Settings"
        case .tripsTaken: "%ld trips"

        // Profile
        case .phoneLockedHint: "Your number is your account. Contact support to change it."
        case .memberSince: "Member since %@"

        // My drivers
        case .myDriversExplainer: "Drivers you rate 5★ land here. Request them directly when they're online — they see your request first."
        case .noFavouritesLong: "Rate a driver 5 stars after a ride, or add one you know by phone number."
        case .addByPhone: "Add by phone number"
        case .addByPhoneBody: "Know a Zuri driver? Enter their number and they'll appear in your list."
        case .addByPhoneHint: "Demo: try 754 123 456 or 765 567 890."
        case .addDriver: "Add driver"
        case .driverAdded: "%@ added to your drivers"
        case .driverNotFound: "No Zuri driver with that number."
        case .notifyWhenOnline: "Notify me when online"
        case .statusOnline: "Online"
        case .statusBusy: "On a trip"
        case .statusOffline: "Offline"
        case .driverNowOnline: "%@ is online now"

        // Driver detail
        case .memberSinceShort: "Since"
        case .rideType: "Ride type"
        case .seats: "%ld seats"
        case .notifyWhenOnlineBody: "Get a notification when %@ comes online."
        case .tripsWithDriver: "%ld trips together"
        case .driverUnavailable: "%@ is unavailable"
        case .removeFromMyDrivers: "Remove from my drivers"
        case .tripsCount: "%@ trips"

        // Saved places
        case .tapToSet: "Tap to set"
        case .addPlace: "Add place"
        case .editPlace: "Edit place"
        case .placeType: "Type"
        case .homeLabel: "Home"
        case .workLabel: "Work"
        case .otherLabel: "Other"
        case .placeLabel: "Label"
        case .placeLabelPlaceholder: "e.g. Mama's house"
        case .location: "Location"
        case .searchPlace: "Search for a place"
        case .savePlace: "Save place"
        case .deletePlace: "Delete place"

        // Promotions
        case .referralTitle: "Invite friends, ride cheaper"
        case .referralBody: "You both get TZS 2,000 off after their first ride."
        case .referralMessage: "Join me on Zuri — zero-commission rides in Dar. Use my code %@ for TZS 2,000 off your first ride: %@"
        case .shareWhatsApp: "Share on WhatsApp"
        case .shareOther: "Share another way"
        case .yourCodes: "Your codes"
        case .used: "Used"
        case .expiresOn: "Expires %@"
        case .promoTerms: "Discounts come from Zuri, never from the driver's fare. One code per ride."

        // Safety
        case .sosDuringTrip: "SOS during a trip"
        case .sosDuringTripBody: "Tap the red SOS button on any live trip to call 112 or alert your contacts with your live location."
        case .emergencyContacts: "Emergency contacts (%ld/3)"
        case .addContact: "Add contact"
        case .maxContacts: "You can add up to 3 contacts."
        case .contactNamePlaceholder: "e.g. Mama"
        case .saveContact: "Save contact"
        case .autoShareTrips: "Auto-share my trips"
        case .autoShareTripsBody: "Send a live trip link to your contacts every time a driver accepts."
        case .safetyTips: "Safety tips"
        case .safetyTip1: "Check the plate on the app matches the car before getting in."
        case .safetyTip2: "Ask the driver your name — they see it on their app."
        case .safetyTip3: "Share your trip with someone you trust."
        case .safetyTip4: "Calls to drivers go through Zuri — your number stays private."

        // Support
        case .chatWhatsApp: "Chat on WhatsApp"
        case .callSupport: "Call support"
        case .supportHours: "Every day 06:00–23:00 · Replies in under 10 minutes"
        case .lastTrip: "Your last trip"
        case .faq: "Common questions"
        case .faqQ1: "How does zero commission work?"
        case .faqA1: "Drivers pay a small flat weekly subscription to use Zuri. We take nothing from your fare, so the driver keeps 100%."
        case .faqQ2: "How is the fare calculated?"
        case .faqA2: "Base + distance + time, fixed at booking within LATRA bands. No surge pricing."
        case .faqQ3: "Can I pay with M-Pesa?"
        case .faqA3: "Yes — M-Pesa, Mixx by Yas, Airtel Money and HaloPesa. Link a wallet under Payments. Cash is always available."
        case .faqQ4: "What if I cancel?"
        case .faqA4: "Free within 2 minutes of a driver accepting. After that a small fee (TZS 500–1,000) goes to the driver. If the driver asked you to cancel, flag it — no fee."
        case .faqQ5: "How do favourite drivers work?"
        case .faqA5: "Rate a driver 5★ and they join My drivers. When they're online you can request them directly and they see your request first."
        case .faqQ6: "Is Zuri available outside Dar?"
        case .faqA6: "Not yet. Tap 'Notify me' on any out-of-zone destination and we'll tell you when we launch there."
        case .legal: "Legal"
        case .termsOfService: "Terms of service"
        case .privacyPolicy: "Privacy policy"

        // Settings
        case .masakiDiorama: "Masaki 3D diorama"
        case .dioramaControlsBody: "Download, prepare and adjust Masaki here. The map stays free of floating diorama controls."
        case .dioramaEnabled: "Show prepared diorama"
        case .driverEye: "Vehicle chase view"
        case .driverEyeBody: "Keep the vehicle centered in the available map space with a wider, tilted view. The camera turns with the vehicle so you always look at its rear. Drag the map or switch off to leave. Uses the trip’s position feed, including simulated movement in demo trips—not Street View imagery."
        case .driverEyeExit: "Exit chase view"
        case .roadRouteUnavailable: "Road directions unavailable. Demo movement is paused."
        case .roadRouteLoading: "Finding a mapped road route…"
        case .mapStyle: "Map style"
        case .mapStyleBody: "Changes the map's lighting and colour. Buildings, places and vehicles stay the same."
        case .mapStyleMonochromeDay: "Monochrome daylight"
        case .mapStyleMonochromeDayBody: "Grey city, bright daytime light"
        case .mapStyleMonochromeDusk: "Monochrome dusk"
        case .mapStyleMonochromeDuskBody: "Grey city, low evening light"
        case .mapStyleNight: "Night"
        case .mapStyleNightBody: "Dark city with lit windows and streets"
        case .mapStyleDawn: "Dawn"
        case .mapStyleDawnBody: "Warm early light with long shadows"
        case .mapStyleColourDay: "Colour daylight"
        case .mapStyleColourDayBody: "Green parks and blue water in full colour"
        case .mapStyleFaded: "Faded"
        case .mapStyleFadedBody: "Soft, pale colour that keeps labels forward"
        case .language: "Language"
        case .notifications: "Notifications"
        case .tripUpdates: "Trip updates"
        case .promoUpdates: "Offers and promotions"
        case .account: "Account"
        case .logOut: "Log out"
        case .logOutConfirmTitle: "Log out of Zuri?"
        case .deleteAccount: "Delete account"
        case .deleteAccountSubtitle: "Removes your data from this device"
        case .deleteAccountConfirmTitle: "Delete your account?"
        case .deleteAccountConfirmBody: "Your profile, saved places, favourite drivers and trip history will be removed. This can't be undone."
        case .deleteAccountConfirm: "Delete everything"

        case .siriGuide: "Siri, Shortcuts & widget"
        case .siriGuideSubtitle: "Book and track rides without opening the app"
        case .siriGuideIntro: "Zuri works with Siri, the Shortcuts app and your Home Screen. Here is everything you can do and the words to say. Speak the phrases in English — Siri does not understand Kiswahili yet."
        case .siriGuideBookTitle: "Book by voice"
        case .siriGuideBookBody: "Ask for a price first, or go straight to a request. Siri remembers the answer, so you can say \"book the comfort one\" after a quote. Home and Work are understood as places."
        case .siriGuideBookPhrase1: "How much is a ride to the airport with Zuri?"
        case .siriGuideBookPhrase2: "Get me a ride to work with Zuri"
        case .siriGuideBookPhrase3: "Book my last Zuri trip again"
        case .siriGuideRideTitle: "During a ride"
        case .siriGuideRideBody: "While a driver is on the way or you are on board, Siri can read the ETA, the car and plate to look for and your start code, cancel (it tells you the fee first), or change the destination."
        case .siriGuideRidePhrase1: "Where is my Zuri driver?"
        case .siriGuideRidePhrase2: "Cancel my Zuri ride"
        case .siriGuideRidePhrase3: "Change my destination to Slipway"
        case .siriGuideScreenTitle: "Talk about what is on screen"
        case .siriGuideScreenBody: "On iOS 27, Siri sees what Zuri is showing, so you can say \"this\", \"him\" or \"here\" instead of repeating details. Every action below also works by name on older iOS."
        case .siriGuideScreen1: "Ride options"
        case .siriGuideScreen1Body: "\"Book the cheapest one\" · \"How long is the bajaji?\" · \"Add a stop at Kariakoo\""
        case .siriGuideScreen2: "Driver on the way"
        case .siriGuideScreen2Body: "\"Call him\" · \"Share my ride with Amina\" · \"What's the plate?\" · \"Add this driver to my drivers\""
        case .siriGuideScreen3: "Ride finished or a receipt"
        case .siriGuideScreen3Body: "\"Tip 1,000 shillings\" · \"Rate this five stars\" · \"Share this receipt\" · \"Book this again\""
        case .siriGuideScreen4: "A place in search or recents"
        case .siriGuideScreen4Body: "\"Save this as Work\" · \"Send this address to Juma\" · \"Take me here\""
        case .siriGuideScreen5: "My drivers"
        case .siriGuideScreen5Body: "\"Request Neema\" · \"Tell me when Hassan is online\""
        case .siriGuideShortcutsTitle: "Build your own in Shortcuts"
        case .siriGuideShortcutsBody: "Every action above is a block in the Shortcuts app: Find a Place, Get a Fare Quote, Request a Ride, Check My Ride, Share My Ride, Call My Driver, Cancel, Change Destination, Tip, Rate, Book Again, Save Place, Add a Stop, Get Receipt and the driver actions. Chain them, put them on the Action Button or in Control Centre, or run them on a schedule, for example a quote to work every weekday at 7:30."
        case .siriGuideOpenShortcuts: "Open Shortcuts"
        case .siriGuideWidgetTitle: "Home Screen widget"
        case .siriGuideWidgetBody: "Four sizes. Small and medium show the live ride, or pickup times for Ride, Bajaji and Boda beside a search button and Home and Work. Large shows the Home sheet. On iOS 27 the full-height size adds your drivers, recents, wallet and past trips; every row opens the matching screen. The widget fills in after you open Zuri once."
        case .siriGuideWidgetStep1: "Touch and hold an empty spot on your Home Screen"
        case .siriGuideWidgetStep2: "Tap Edit, then Add Widget, and search for Zuri"
        case .siriGuideWidgetStep3: "Pick a size and tap Add Widget"
        case .siriGuideAvailability: "Voice phrases and the widget work on iOS 18 and later. On-screen awareness and the full-height widget need iOS 27."
        case .siriGuideTryIt: "Try it now"

        // Mobile money, ID verification, billboards
        case .topUpChooseWallet: "Choose a wallet"
        case .topUpEnterAmount: "Enter an amount"
        case .topUpAddFrom: "Add %@ from %@"
        case .topUpNewBalance: "New balance %@"
        case .topUpMinimumHint: "Minimum %@"
        case .notLinked: "Not linked"
        case .linkShort: "Link"
        case .linked: "Linked"
        case .linkWithNumber: "Link %@"
        case .useAnotherNumber: "Use another number"
        case .autoTopUp: "Auto top-up"
        case .autoTopUpOff: "Off"
        case .autoTopUpSummary: "Below %@, add %@ from %@"
        case .autoTopUpTitle: "Auto top-up"
        case .autoTopUpBody: "When your balance runs low, Zuri sends one PIN prompt to your phone to add money. Nothing moves until you approve it."
        case .autoTopUpThreshold: "When balance drops below"
        case .autoTopUpAmount: "Add this amount"
        case .autoTopUpFrom: "From"
        case .autoTopUpSave: "Save"
        case .autoTopUpNeedsWallet: "Link a mobile money wallet first."
        case .autoTopUpInvalid: "Amounts must be at least TZS 1,000."
        case .autoTopUpDone: "Auto top-up: %@ added"
        case .walletAutoTopUpTitle: "Auto top-up from %@"
        case .mmWaitingRow: "Waiting for approval"
        case .mmCheckPhoneTitle: "Check your phone"
        case .mmCheckPhoneBody: "Approve %@ on the %@ PIN prompt. You don't need to open any app."
        case .mmRidePromptBody: "Approve %@ on the %@ PIN prompt to pay for this ride."
        case .mmExpiresIn: "Prompt expires in %@"
        case .mmKeepOpen: "You can keep this screen open or leave it. We'll update your wallet either way."
        case .mmTestMode: "Test mode"
        case .mmTestModeBody: "No real money moves. This is what %@ will show on your phone once payments go live."
        case .mmPromptText: "Pay %@ to ZURI?\nEnter PIN to confirm"
        case .mmPromptPin: "PIN"
        case .mmPromptSend: "Send"
        case .mmPromptCancel: "Cancel"
        case .mmPromptHint: "Any 4 digits approve. 0000 tests a wrong PIN."
        case .mmSimulateInsufficient: "Test: not enough money"
        case .mmApprovedTitle: "%@ added"
        case .mmApprovedBody: "New balance %@"
        case .mmReference: "Reference"
        case .mmDone: "Done"
        case .mmChangeAmount: "Change amount"
        case .mmFailDeclined: "Payment cancelled"
        case .mmFailDeclinedBody: "The request was cancelled on your phone. No money moved."
        case .mmFailWrongPin: "Wrong PIN"
        case .mmFailWrongPinBody: "The PIN didn't match. No money moved."
        case .mmFailTimeout: "Prompt expired"
        case .mmFailTimeoutBody: "We didn't get your approval in time. No money moved."
        case .mmFailFunds: "Not enough money"
        case .mmFailFundsBody: "Your %@ balance is too low for this amount."
        case .mmFailOther: "Payment didn't go through"
        case .mmFailOtherBody: "No money moved. Try again in a moment."
        case .mmStartFailed: "Couldn't reach the payment service. Check your connection and try again."
        case .idVerify: "Verify with ID"
        case .idVerified: "ID verified"
        case .idVerifySubtitle: "Scan any ID or passport to fill in your details"
        case .idPrimerTitle: "Verify with your ID"
        case .idPrimerSubtitle: "Scan your NIDA card, driving licence or any passport. We fill in your details for you."
        case .idPrimerBullet1: "Works with NIDA cards, driving licences and passports from any country."
        case .idPrimerBullet2: "Read on your phone. The picture of your ID is never uploaded or saved."
        case .idPrimerBullet3: "Drivers see a verified badge, never your ID details."
        case .idScanAction: "Scan my ID"
        case .idSkip: "Skip for now"
        case .idScanTitle: "Scan your ID"
        case .idScanHintPassport: "For passports, show the photo page with the two lines at the bottom."
        case .idScanHintAlign: "Show your ID to the camera. Any angle works."
        case .idScanHintSteady: "Found it. Hold still…"
        case .idScanHintCloser: "Move a little closer"
        case .idScanHintGlare: "Tilt the card slightly to avoid glare"
        case .idScanHintReading: "Reading your details…"
        case .idScanCaptured: "Got it"
        case .idCameraDeniedTitle: "Camera access is off"
        case .idCameraDeniedBody: "Allow camera access in Settings to scan your ID."
        case .idNoCameraTitle: "No camera found"
        case .idNoCameraBody: "ID verification needs a camera. Try again on a phone with a camera."
        case .idOpenSettings: "Open Settings"
        case .idReviewTitle: "Check your details"
        case .idReviewSubtitle: "Everything below was read from your ID on your phone. If anything is wrong, scan again."
        case .idChecksumOK: "Machine-readable lines verified"
        case .idGivenNames: "First and middle names"
        case .idSurname: "Surname"
        case .idDocumentNumber: "ID or passport number"
        case .idNationality: "Nationality"
        case .idSex: "Sex"
        case .idSexFemale: "Female"
        case .idSexMale: "Male"
        case .idSexUnspecified: "Not specified"
        case .idDateOfBirth: "Date of birth"
        case .idExpiry: "Expiry date"
        case .idCheckField: "Check this: we couldn't read it clearly"
        case .idUseCardPhoto: "Use the card photo as my profile photo"
        case .idUseName: "Use this name on my profile"
        case .idConfirm: "Confirm details"
        case .idRescan: "Scan again"
        case .idMissingError: "We couldn't read your name, ID number and date of birth clearly. Scan again in good light."
        case .idUnderageError: "You need to be 18 or older to verify with Zuri."
        case .idExpiredError: "This ID has expired. Scan a valid ID to verify."
        case .idSaved: "ID verified"
        case .idKindNida: "NIDA card"
        case .idKindPassport: "Passport"
        case .idKindNationalID: "National ID"
        case .idKindDriving: "Driving licence"
        case .idKindResidence: "Residence permit"
        case .idKindOther: "ID document"
        case .idDocumentType: "Document"
        case .idStatusBody: "Verified on %@ with your %@."
        case .idRemove: "Remove verification"
        case .adSponsored: "Sponsored"
        case .adTestBadge: "Test ad"
        case .adKfcHeadline: "2 pieces + chips"
        case .adKfcOffer: "TZS 7,000 at any Dar es Salaam branch. Ride there with Zuri."
        case .adNearestBranch: "Nearest branch: %@"
        case .adRideThere: "Ride to %@"
        case .adDisclaimer: "Sample advert for advertiser demos."
        case .walletEnterCode: "Enter the code"
        case .walletCodeSentTo: "We sent a 6-digit code by SMS to %@."
        case .walletTestCode: "Test mode, SMS not connected yet. Your code is %@"
        case .walletDetectedAs: "This is a %@ number"
        case .walletDetectedName: "Registered to %@"
        case .walletWrongNetwork: "This number is on %@, not %@."
        case .walletSwitchTo: "Link as %@ instead"
        case .walletUnknownNetwork: "We couldn't recognise this network. Check the number."
        case .walletSendCode: "Send code"
        case .walletResendCode: "Resend code"
        case .walletResendIn: "Resend in %@"
        case .walletEditNumber: "Edit number"
        case .walletVerifiedToast: "%@ linked and verified"
        case .walletNeedsVerify: "Verify with SMS"
        case .walletOwnershipNote: "We text a code to prove the number is yours. You'll still approve every payment with your PIN."
        case .changeWalletNumber: "Use a different number"
        case .topUpStep1: "Pick your wallet"
        case .topUpStep2: "Type the amount"
        case .topUpStep3: "Enter your %@ PIN on your phone"
        case .changeNumberTitle: "Change %@ number"
        case .currentNumber: "Currently linked: %@"
        case .unlinkWallet: "Unlink this wallet"
        case .signInTitle: "Welcome to Zuri"
        case .signInSubtitle: "Sign in to save your rides, wallet and places securely to your account."
        case .signInGoogle: "Continue with Google"
        case .signInPhoneInstead: "Your phone number is added next, for drivers and mobile money."
        case .signInTerms: "By continuing you agree to Zuri's Terms and Privacy Policy."
        case .signInFailed: "Sign-in didn't finish. Please try again."
        case .signedInAs: "Signed in as %@"
        case .signOutGoogle: "Sign out"
        case .accountSynced: "Account saved securely"
        case .yourRideNow: "Your ride now"
        case .routeUpdated: "Route updated, driver notified"
        case .changingThisStop: "Search for a new place…"
        case .tapToChange: "Tap to change"
        case .changeRoute: "Change route"
        case .planYourTrip: "Plan your trip"
        case .searchPickup: "Search pickup"
        case .newFare: "New fare"
        case .updateRoute: "Update route"
        case .findingAddress: "Finding address…"
        case .chatWithDriver: "Chat with driver"
        case .chatAutoTranslate: "Messages translate automatically"
        case .chatEmpty: "Let your driver know you're on your way out. Messages are translated between Swahili and English."
        case .chatQuickComing: "I'm coming out now"
        case .chatQuickHere: "I'm at the pickup"
        case .chatQuickFiveMin: "Give me 5 minutes"
        case .chatQuickWhere: "Where are you?"
        case .chatPlaceholder: "Message"
        case .chatSend: "Send"
        case .chatTranslated: "Translated"
        }
    }
}
