import Foundation

extension Strings {
    static func swahili(_ key: LKey) -> String {
        switch key {
        case .tabHome: "Mwanzo"
        case .tabActivity: "Shughuli"

        // Offline maps
        case .offlineMaps: "Ramani bila intaneti"
        case .offlineMapsBody: "Hifadhi eneo kabla ya kusafiri. Pakua mara moja kwa Wi-Fi, kisha tazama mitaa na majengo bila kutumia data ya simu."
        case .offlineWiFiOnly: "Pakua kwa Wi-Fi pekee"
        case .offlineDownloadedOnly: "Tumia ramani zilizohifadhiwa tu"
        case .offlineOnlyBody: "Inazuia upakuaji wote wa ramani za Mapbox. Maeneo yasiyohifadhiwa yanaweza kuwa tupu. Zima ili kupakua au kusasisha eneo."
        case .offlineSlipway: "Slipway na ufukwe"
        case .offlineSlipwayDetail: "Eneo la pwani la km 2 karibu na Slipway"
        case .offlinePeninsula: "Rasi ya Msasani"
        case .offlinePeninsulaDetail: "Masaki, Oyster Bay na Msasani · takribani km 7 kwa upana"
        case .offlineCentral: "Dar es Salaam ya kati"
        case .offlineCentralDetail: "Katikati ya jiji, Upanga, Kariakoo na maeneo jirani · takribani km 13 kwa upana"
        case .offlineDownload: "Pakua eneo"
        case .offlineUpdate: "Sasisha"
        case .offlineReady: "Inapatikana bila intaneti"
        case .offlinePreparing: "Inahifadhi mwonekano wa ramani…"
        case .offlineDownloading: "Inahifadhi mitaa na majengo…"
        case .offlinePaused: "Imesitishwa — data iliyopakuliwa imehifadhiwa"
        case .offlineResume: "Endelea kupakua"
        case .offlineFailed: "Upakuaji haujakamilika. Angalia intaneti na nafasi ya hifadhi, kisha jaribu tena. Maeneo makubwa yanaweza kufikia kikomo cha mtoa ramani."
        case .offlineRemoveFailed: "Imeshindwa kuondoa eneo. Jaribu tena."
        case .offlineRemoveTitle: "Ondoa eneo lililopakuliwa?"
        case .offlineRemoveBody: "Eneo halitapatikana tena bila intaneti. Data inayotumiwa na maeneo mengine inaweza kubaki kwenye hifadhi."
        case .offlineInventoryFailed: "Imeshindwa kusoma maeneo yaliyopakuliwa. Jaribu tena."
        case .offlineDisableOnly: "Zima “Tumia ramani zilizohifadhiwa tu” ili kupakua."
        case .offlineConnect: "Unganisha intaneti ili kupakua eneo."
        case .offlineNeedWiFi: "Unganisha Wi-Fi bila Hali ya Data Kidogo, au zima chaguo la Wi-Fi pekee."
        case .offlineLimitations: "Ramani zina maelezo ya mitaa hadi ukuzaji wa 16. Ukikuza zaidi, maelezo yaliyohifadhiwa hutumika. Acha Zuri wazi wakati wa kupakua; ukitoka, upakuaji husitishwa. Utafutaji, safari za moja kwa moja, maelekezo na malipo bado yanahitaji intaneti. Ukubwa unaonyeshwa ni wa data iliyohifadhiwa, ambayo inaweza kutumiwa na maeneo kadhaa."
        case .offlineBundled: "Majengo na mandhari maalumu ya 3D ya Slipway tayari yapo ndani ya Zuri. Hakuna haja ya kupakua mifano mingine."
        case .offlinePartial: "Eneo halijakamilika"
        case .offlineProgress: "%d%% · %@ imehifadhiwa"

        // Common
        case .back: "Rudi"
        case .close: "Funga"
        case .cancel: "Ghairi"
        case .continueAction: "Endelea"
        case .skip: "Ruka"
        case .change: "Badilisha"
        case .remove: "Ondoa"
        case .delete: "Futa"
        case .clear: "Futa"
        case .gotIt: "Sawa, nimeelewa"
        case .verify: "Thibitisha"
        case .copy: "Nakili"
        case .copied: "Imenakiliwa"
        case .seeAll: "Ona zote"
        case .saved: "Imehifadhiwa"
        case .saveChanges: "Hifadhi mabadiliko"
        case .menu: "Menyu"
        case .recentre: "Rudisha ramani"
        case .request: "Omba"
        case .notNow: "Si sasa"
        case .tryAgain: "Jaribu tena"
        case .backToHome: "Rudi mwanzo"
        case .minutesShort: "dak %ld"
        case .minuteUnit: "dak"
        case .yourLocation: "Mahali ulipo"
        case .recommended: "Inapendekezwa"
        case .darEsSalaam: "Dar es Salaam"
        case .madeInDar: "Imetengenezwa Dar es Salaam"
        case .nearPlace: "Karibu na %@"
        case .droppedPin: "Alama iliyowekwa"

        // Splash & language
        case .splashTagline: "Safari bila kamisheni, Dar"
        case .splashFooter: "Dereva anabaki na 100% ya kila nauli"
        case .languageTitle: "Chagua lugha yako"
        case .languageSubtitle: "Unaweza kubadilisha wakati wowote kwenye Mipangilio."

        // Phone & OTP
        case .phoneTitle: "Namba yako ya simu?"
        case .phoneSubtitle: "Tutakutumia msimbo wa tarakimu 6 kwa SMS."
        case .phoneLabel: "Namba ya simu"
        case .phoneHint: "Namba za Tanzania pekee (06 / 07)."
        case .sendCode: "Tuma msimbo"
        case .otpTitle: "Weka msimbo"
        case .otpSubtitle: "Umetumwa kwa SMS kwenda %@"
        case .otpResendIn: "Tuma tena baada ya %@"
        case .otpResend: "Tuma msimbo tena"
        case .otpChangeNumber: "Badilisha namba"
        case .otpInvalid: "Msimbo haukufanana. Jaribu tena."
        case .otpDemoHint: "Onyesho: tarakimu zozote 6 zinafanya kazi."

        // Profile setup
        case .profileTitle: "Tuambie jina lako"
        case .profileSubtitle: "Dereva anaona jina lako la kwanza anapokubali safari."
        case .fullName: "Jina kamili"
        case .fullNamePlaceholder: "mf. Asha Mohamed"
        case .emailOptional: "Barua pepe (si lazima)"
        case .profilePrivacy: "Namba yako haionyeshwi kwa dereva. Simu zinaunganishwa kupitia Zuri."

        // Permission primers
        case .locationTitle: "Ruhusu eneo"
        case .locationSubtitle: "Ili tuweke sehemu ya kuchukuliwa na kuonyesha madereva walio karibu."
        case .locationBullet1: "Sehemu sahihi ya kuchukuliwa bila kuandika anwani"
        case .locationBullet2: "Muda halisi wa kufika wa madereva walio karibu nawe"
        case .locationBullet3: "Wakati unatumia programu tu"
        case .allowLocation: "Ruhusu eneo"
        case .locationDeniedHint: "Eneo limezimwa. Bado unaweza kuweka sehemu ya kuchukuliwa kwenye ramani, au kuliwasha kwenye Mipangilio."
        case .notificationsTitle: "Baki na taarifa"
        case .notificationsSubtitle: "Tutakuarifu kuhusu safari zako tu."
        case .notificationsBullet1: "Dereva anapokubali na anapofika"
        case .notificationsBullet2: "Dereva wako pendwa anapokuwa mtandaoni"
        case .notificationsBullet3: "Uthibitisho wa malipo na risiti"
        case .allowNotifications: "Ruhusu arifa"

        // Home
        case .goodMorning: "Habari za asubuhi"
        case .goodAfternoon: "Habari za mchana"
        case .goodEvening: "Habari za jioni"
        case .whereTo: "Unaenda wapi?"
        case .searchDestinationHint: "Tafuta unakoenda"
        case .favouritesOnline: "%ld mtandaoni"
        case .demoLocation: "Eneo la onyesho"
        case .addHome: "Ongeza nyumbani"
        case .addWork: "Ongeza kazini"
        case .myDrivers: "Madereva wangu"
        case .noFavouritesTitle: "Bado hauna madereva pendwa"
        case .noFavouritesBody: "Mpe dereva nyota 5 ili amuongezwe hapa."
        case .recent: "Za karibuni"
        case .noRecents: "Sehemu ulizoenda karibuni zitaonekana hapa."
        case .offlineBanner: "Hauko mtandaoni"
        case .serviceRide: "Gari"
        case .serviceBajaji: "Bajaji"
        case .serviceBoda: "Boda"
        case .letsGo: "Twende!"
        case .driversNearbyCount: "Madereva %ld karibu"

        // Search
        case .pickupLabel: "Kuchukuliwa"
        case .popularPlaces: "Maarufu Dar"
        case .setOnMap: "Weka eneo kwenye ramani"
        case .stopLabel: "Kituo %ld"
        case .addStop: "Ongeza kituo"
        case .addAnotherStop: "Ongeza kituo kingine"
        case .stopsCount: "Vituo %ld"
        case .removeStop: "Ondoa kituo"
        case .reorderRoute: "Panga vituo upya"
        case .reorderRouteHint: "Buruta sehemu yoyote, ikiwemo ya kuchukuliwa na unakoenda, kubadilisha mpangilio."
        case .moveEarlier: "Sogeza mbele"
        case .moveLater: "Sogeza nyuma"
        case .whereToNext: "Kisha wapi?"
        case .setStopTitle: "Weka kituo"
        case .confirmStopHere: "Ongeza kituo hapa"
        case .chooseDestination: "Chagua unakoenda"
        case .maxStopsReached: "Unaweza kuongeza vituo hadi %ld"
        case .viaStops: "kupitia vituo %ld"
        case .viaOneStop: "kupitia kituo 1"
        case .searchingPlaces: "Inatafuta…"
        case .noResultsTitle: "Hakuna sehemu iliyopatikana"
        case .noResultsBody: "Jaribu jina la eneo, barabara au alama — au weka kwenye ramani."
        case .requestingDriver: "Unamuomba %@"
        case .chooseDestinationFirst: "Chagua unakoenda kwanza."

        // Set on map & confirm pickup
        case .setPickupTitle: "Weka sehemu ya kuchukuliwa"
        case .setDestinationTitle: "Weka unakoenda"
        case .confirmPickupHere: "Nichukue hapa"
        case .confirmDestinationHere: "Nenda hapa"
        case .outOfZoneShort: "Nje ya eneo la huduma la Dar es Salaam"
        case .confirmPickupTitle: "Thibitisha sehemu ya kuchukuliwa"
        case .pickupNotePlaceholder: "Ujumbe kwa dereva, mf. geti la 2, jengo la bluu"
        case .confirmPickup: "Thibitisha"

        // Ride options
        case .chooseRide: "Chagua safari"
        case .fareDetails: "Maelezo"
        case .pickupInMinutes: "Anafika baada ya dak %ld"
        case .pickupInOneMinute: "Anafika baada ya dak 1"
        case .dropoffAtTime: "Kushuka saa %@"
        case .pickupUnavailable: "Hakuna madereva karibu"
        case .dropoffUnavailable: "Muda wa kushuka haupatikani"
        case .expandRideOptions: "Chaguo zaidi za safari"
        case .collapseRideOptions: "Fupisha chaguo za safari"
        case .fewDriversNearby: "Madereva wachache karibu"
        case .promoCode: "Msimbo wa punguzo"
        case .willAskDriverFirst: "Tutamuuliza %@ kwanza, kisha madereva wengine ikibidi."
        case .requestDriver: "Omba %@"
        case .requestRide: "Omba safari"
        case .requestTier: "Omba %@"
        case .tierEconomy: "Economy"
        case .tierComfort: "Comfort"
        case .tierPremium: "Premium"
        case .tierBajaji: "Bajaji"
        case .tierBoda: "Boda"
        case .tierEconomyDescription: "Hatchback za kila siku, bei nafuu"
        case .tierComfortDescription: "Sedan za starehe, safari tulivu"
        case .tierPremiumDescription: "Minivan za kifahari, nafasi kwa sita"
        case .tierBajajiDescription: "Magurudumu matatu, haraka kwenye foleni"
        case .tierBodaDescription: "Pikipiki, haraka zaidi kwa mtu mmoja"

        // Zero commission
        case .badgeDriverReceives100: "Dereva anapata 100% ya nauli"
        case .badgeDriverReceivesAmount: "Dereva anapata: %@ (100%%)"
        case .badgeDriverReceived: "Dereva amepata: %@ (100%%)"
        case .zeroCommissionTitle: "Kamisheni sifuri"
        case .zeroCommissionBody: "Zuri haichukui sehemu yoyote ya nauli yako. Kila shilingi unayolipa inaenda kwa dereva — ndiyo maana madereva wanakubali haraka na kughairi mara chache."
        case .zeroCommissionPoint1Title: "Madereva wanabaki na yote"
        case .zeroCommissionPoint1Body: "Hakuna makato ya 20–25%. Nauli unayoiona ndiyo anayobaki nayo."
        case .zeroCommissionPoint2Title: "Nauli kwa viwango vya LATRA"
        case .zeroCommissionPoint2Body: "Bei zinafuata viwango vya mdhibiti — hakuna mshtuko wa bei."
        case .zeroCommissionPoint3Title: "Madereva bora wanabaki"
        case .zeroCommissionPoint3Body: "Malipo ya haki yanawaweka madereva bora Zuri, na unaweza kuchagua unaowapenda."
        case .exampleFare: "Mfano: unalipa → dereva anapata"

        // Fare breakdown
        case .fareBreakdownTitle: "Mchanganuo wa nauli"
        case .baseFare: "Nauli ya msingi"
        case .distanceFare: "Umbali (%@)"
        case .timeFare: "Muda (dak %ld)"
        case .promoDiscount: "Punguzo"
        case .tip: "Bahasha"
        case .total: "Jumla"
        case .fareBreakdownNote: "Nauli inapangwa wakati wa kuagiza ndani ya viwango vya LATRA. Kusubiri zaidi ya dakika 5 kunaweza kuongeza TZS 100/dak."

        // Payment
        case .payWith: "Lipa kwa"
        case .cashDetail: "Mlipe dereva moja kwa moja"
        case .addMobileMoney: "Ongeza pesa za simu"
        case .payment: "Malipo"
        case .payments: "Malipo"
        case .defaultMethod: "Njia chaguo-msingi"
        case .unlink: "Ondoa"
        case .paymentsNote: "Pesa taslimu inapatikana kila wakati. Pesa za simu zinakatwa baada ya safari kuisha, na dereva bado anapata 100%."
        case .linkWallet: "Unganisha %@"
        case .useAccountPhone: "Tumia namba yangu ya Zuri (%@)"
        case .walletNumber: "Namba ya pochi"
        case .linkWalletNote: "Utaidhinisha kila malipo kwa PIN yako kwenye simu. Zuri haioni PIN yako kamwe."
        case .linkAction: "Unganisha akaunti"

        // Zuri wallet
        case .wallet: "Pochi ya Zuri"
        case .walletBalance: "Salio"
        case .walletBalanceDetail: "Salio %@"
        case .walletEmptyDetail: "Weka pesa ulipe mara moja"
        case .walletInsufficient: "Salio halitoshi · %@"
        case .topUp: "Weka pesa"
        case .topUpWallet: "Weka pesa kwenye pochi"
        case .topUpAmount: "Kiasi"
        case .topUpCustomAmount: "Kiasi kingine"
        case .topUpFrom: "Lipa kutoka"
        case .topUpNoRails: "Unganisha akaunti ya pesa za simu ili kujaza pochi yako."
        case .topUpLinkRail: "Unganisha pesa za simu"
        case .topUpConfirm: "Ongeza %@"
        case .topUpDone: "%@ imeongezwa kwenye pochi yako"
        case .topUpMinimum: "Kiasi cha chini ni %@."
        case .topUpMaximum: "Kiasi cha juu kwa sasa ni %@."
        case .walletHistory: "Shughuli"
        case .walletNoHistory: "Kuweka pesa na malipo ya safari vitaonekana hapa."
        case .walletTopUpTitle: "Kuweka pesa kutoka %@"
        case .walletRidePayment: "Safari ya %@"
        case .walletRefund: "Marejesho"
        case .walletExplainer: "Salio la kabla lililoshikiliwa na Zuri. Safari zinalipwa mara moja zinapoisha, na dereva bado anapata 100%."
        case .walletPaid: "Imelipwa kutoka pochi"
        case .walletShortBody: "Pochi yako ina %@. Weka pesa au chagua njia nyingine ya kulipa."
        case .walletShortTopUp: "Weka pesa kwenye pochi"
        case .payWithWallet: "Lipa %@ kutoka pochi"
        case .walletAfterRide: "Inakatwa mara moja baada ya safari"

        // Promo codes
        case .enterCode: "Weka msimbo"
        case .applyCode: "Tumia msimbo"
        case .promoHint: "Jaribu KARIBU upate punguzo la 20% safari ya kwanza."
        case .promoInvalid: "Msimbo huo si sahihi au umeshatumika."
        case .promoKaribuTitle: "Punguzo la 20% safari ya kwanza"
        case .promoKaribuDetail: "Hadi TZS 3,000. Aina yoyote ya safari."
        case .promoTwende10Title: "Punguzo la 10% mwezi huu"
        case .promoTwende10Detail: "Hadi TZS 2,000. Matumizi moja."

        // Out of zone
        case .outOfZoneTitle: "Bado hatupo hapo"
        case .outOfZoneBody: "Zuri inahudumia Dar es Salaam pekee kwa sasa. %@ ipo nje ya eneo letu — tutakuambia tukifika."
        case .notifyMeZone: "Nijulishe mtakapoanza hapo"
        case .notifyMeZoneConfirmed: "Tutakujulisha Zuri itakapofika %@."
        case .notifyMeZoneAlready: "Utajulishwa tutakapoanza hapo"
        case .chooseAnotherPlace: "Chagua sehemu nyingine"

        // Quick request
        case .awayFromYou: "Umbali"
        case .pickupEta: "Anafika baada ya"
        case .viewProfile: "Ona wasifu"

        // Searching / no drivers
        case .askingDriver: "Tunamuuliza %@…"
        case .findingDriver: "Tunatafuta dereva wa %@…"
        case .usuallyUnder: "kawaida chini ya dakika"
        case .cancelRequest: "Ghairi ombi"
        case .noDriversTitle: "Hakuna madereva kwa sasa"
        case .noDriversBody: "Hakuna dereva wa %@ aliyekubali karibu. Jaribu tena, au chagua aina nyingine."
        case .tryAnotherRide: "Jaribu aina nyingine"
        case .notifyWhenDrivers: "Nijulishe madereva wakipatikana"

        // Driver en route / arrived
        case .driverOnTheWay: "%@ anakuja"
        case .driverArrivedTitle: "%@ amefika"
        case .meetAtPickup: "Mkutane %@"
        case .arrivingIn: "Anafika baada ya dak %ld"
        case .hereNow: "Yupo hapa"
        case .ridePINTitle: "PIN ya safari yako"
        case .ridePINBody: "Mwambie %@ namba hii kabla ya kuingia. Safari huanza tu baada ya kuiweka."
        case .ridePINArrivedBody: "Hakikisha namba ya gari, kisha msomee %@ namba hii kuanza safari."
        case .ridePINAccessibility: "PIN ya safari %@"
        case .call: "Piga simu"
        case .message: "Ujumbe"
        case .favourite: "Pendwa"
        case .addFavourite: "Ongeza pendwa"
        case .cancelRide: "Ghairi safari"
        case .plateNumber: "Namba ya gari"
        case .shareTrip: "Shiriki safari"
        case .sos: "SOS"
        case .shareTripMessage: "Nasafiri na %@ (namba %@) kuelekea %@ kupitia Zuri. Fuatilia safari yangu: %@"

        // In trip
        case .headingTo: "Unaelekea %@"
        case .inTraffic: "Kwenye foleni"
        case .movingWell: "Safari inaenda vizuri"
        case .trafficMinutes: "dak %ld kwenye foleni"
        case .remaining: "zimebaki"
        case .fareLabel: "Nauli"
        case .changeDestination: "Badilisha unakoenda"
        case .changeDestinationNote: "Nauli itakadiriwa upya kwa njia mpya. Dereva anajulishwa mara moja."
        case .destinationChanged: "Unakoenda kumebadilishwa kuwa %@"

        // Cancellation
        case .cancelReasonTitle: "Kwa nini unaghairi?"
        case .cancelReasonBody: "Hii inatusaidia kuwawajibisha madereva."
        case .cancelWaitTooLong: "Nimesubiri muda mrefu"
        case .cancelDriverNotMoving: "Dereva hasogei"
        case .cancelWrongPickup: "Sehemu ya kuchukuliwa si sahihi"
        case .cancelChangedPlans: "Mipango yangu imebadilika"
        case .cancelDriverAsked: "Dereva ameniomba nighairi"
        case .cancelOther: "Sababu nyingine"
        case .cancellationFeeNotice: "Ada ya kughairi ya %@ inatozwa kwa sababu dereva tayari anakuja."
        case .driverAskedNotice: "Hakuna ada. Tutamfuatilia dereva."
        case .cancelWithFee: "Ghairi (ada %@)"
        case .confirmCancel: "Thibitisha kughairi"
        case .keepRide: "Endelea na safari"
        case .cancelledWithFee: "Safari imeghairiwa. Ada ya %@ itaongezwa safari ijayo."
        case .cancelledNoFee: "Safari imeghairiwa. Hakuna ada."
        case .cancelledLabel: "Imeghairiwa"
        case .cancellationReason: "Sababu"
        case .cancellationFee: "Ada ya kughairi"

        // SOS
        case .sosTitle: "Dharura"
        case .sosBody: "Chagua wa kumfikia. Maelezo ya safari yako yako tayari kushirikiwa."
        case .sosCallPolice: "Piga polisi (112)"
        case .sosConfirmCall: "Upige 112 sasa? Tumia kwa dharura halisi tu."
        case .sosCallNow: "Ndiyo, piga 112"
        case .sosAlertContacts: "Arifu wasiliani wa dharura (%ld)"
        case .sosContactsAlerted: "Wasiliani wamearifiwa na safari yako ya moja kwa moja"
        case .addEmergencyContacts: "Ongeza wasiliani wa dharura"

        // Completion & payment
        case .tripCompleteTitle: "Umefika"
        case .addTip: "Ongeza bahasha"
        case .noTip: "Hapana"
        case .tipNote: "100% ya bahasha inaenda kwa dereva."
        case .payDriverInCash: "Mlipe dereva taslimu"
        case .tapToPay: "Bonyeza hapa chini kulipa"
        case .paymentPendingBody: "Idhinisha ombi kwenye simu yako"
        case .paymentConfirmed: "Malipo yamethibitishwa"
        case .paymentFailed: "Malipo hayakufanikiwa"
        case .paymentFailedBody: "Malipo hayakupita. Jaribu tena, au mlipe dereva taslimu."
        case .confirmCashPaid: "Nimelipa %@ taslimu"
        case .retryPayment: "Jaribu malipo tena"
        case .payWithMethod: "Lipa kwa %@"
        case .payCashInstead: "Lipa taslimu badala yake"
        case .waitingForConfirmation: "Tunasubiri uthibitisho…"

        // Rating
        case .rateDriver: "Safari yako na %@ ilikuwaje?"
        case .rateTrip: "Safari yako ilikuwaje?"
        case .whatWentWrong: "Nini hakikuenda sawa?"
        case .ratingReasonRoute: "Njia"
        case .ratingReasonDriving: "Uendeshaji"
        case .ratingReasonVehicle: "Gari"
        case .ratingReasonBehaviour: "Tabia"
        case .ratingReasonLate: "Kuchelewa"
        case .ratingReasonPrice: "Bei"
        case .addToMyDrivers: "Mwongeze %@ kwenye madereva wangu"
        case .addToMyDriversShort: "Ongeza kwenye madereva wangu"
        case .submitRating: "Tuma tathmini"
        case .thanksForRating: "Asante! Tathmini yako inasaidia abiria wengine."

        // History & receipt
        case .tripHistory: "Historia ya safari"
        case .tripHistorySubtitle: "Risiti na safari zilizopita"
        case .noTripsTitle: "Bado hauna safari"
        case .noTripsBody: "Safari zako na risiti zitaonekana hapa."
        case .receipt: "Risiti"
        case .dropoffLabel: "Kushuka"
        case .latraNotice: "Risiti ya kielektroniki iliyotolewa chini ya kanuni za LATRA za usafiri wa mtandaoni. Ihifadhi kwa kumbukumbu."
        case .shareReceipt: "Shiriki risiti (PDF)"
        case .prepareReceipt: "Andaa risiti (PDF)"
        case .rebook: "Agiza tena"
        case .reportIssue: "Ripoti tatizo"

        // Menu
        case .profile: "Wasifu"
        case .myDriversSubtitle: "Pendwa na maombi ya moja kwa moja"
        case .onlineCount: "%ld mtandaoni"
        case .savedPlaces: "Sehemu zilizohifadhiwa"
        case .savedPlacesSubtitle: "Nyumbani, kazini na zaidi"
        case .promotions: "Punguzo"
        case .promotionsSubtitle: "Misimbo na kuwaalika wengine"
        case .safetyCentre: "Kituo cha usalama"
        case .safetySubtitle: "Wasiliani wa dharura na SOS"
        case .support: "Msaada"
        case .supportSubtitle: "Maswali, WhatsApp, simu"
        case .settings: "Mipangilio"
        case .tripsTaken: "Safari %ld"

        // Profile
        case .phoneLockedHint: "Namba yako ndiyo akaunti yako. Wasiliana na msaada kuibadilisha."
        case .memberSince: "Mwanachama tangu %@"

        // My drivers
        case .myDriversExplainer: "Madereva unaowapa nyota 5 wanaingia hapa. Waombe moja kwa moja wakiwa mtandaoni — wanaona ombi lako kwanza."
        case .noFavouritesLong: "Mpe dereva nyota 5 baada ya safari, au mwongeze unayemjua kwa namba ya simu."
        case .addByPhone: "Ongeza kwa namba ya simu"
        case .addByPhoneBody: "Unamjua dereva wa Zuri? Weka namba yake na ataonekana kwenye orodha yako."
        case .addByPhoneHint: "Onyesho: jaribu 754 123 456 au 765 567 890."
        case .addDriver: "Ongeza dereva"
        case .driverAdded: "%@ ameongezwa kwenye madereva wako"
        case .driverNotFound: "Hakuna dereva wa Zuri mwenye namba hiyo."
        case .notifyWhenOnline: "Nijulishe akiwa mtandaoni"
        case .statusOnline: "Mtandaoni"
        case .statusBusy: "Yuko safarini"
        case .statusOffline: "Hayupo"
        case .driverNowOnline: "%@ yuko mtandaoni sasa"

        // Driver detail
        case .memberSinceShort: "Tangu"
        case .rideType: "Aina ya safari"
        case .seats: "Viti %ld"
        case .notifyWhenOnlineBody: "Pata arifa %@ akiwa mtandaoni."
        case .tripsWithDriver: "Safari %ld pamoja"
        case .driverUnavailable: "%@ hapatikani"
        case .removeFromMyDrivers: "Ondoa kwenye madereva wangu"
        case .tripsCount: "safari %@"

        // Saved places
        case .tapToSet: "Bonyeza kuweka"
        case .addPlace: "Ongeza sehemu"
        case .editPlace: "Hariri sehemu"
        case .placeType: "Aina"
        case .homeLabel: "Nyumbani"
        case .workLabel: "Kazini"
        case .otherLabel: "Nyingine"
        case .placeLabel: "Jina"
        case .placeLabelPlaceholder: "mf. Kwa Mama"
        case .location: "Eneo"
        case .searchPlace: "Tafuta sehemu"
        case .savePlace: "Hifadhi sehemu"
        case .deletePlace: "Futa sehemu"

        // Promotions
        case .referralTitle: "Alika marafiki, safiri kwa bei nafuu"
        case .referralBody: "Nyote mnapata punguzo la TZS 2,000 baada ya safari yake ya kwanza."
        case .referralMessage: "Jiunge nami Zuri — safari bila kamisheni Dar. Tumia msimbo wangu %@ upate punguzo la TZS 2,000 safari ya kwanza: %@"
        case .shareWhatsApp: "Shiriki WhatsApp"
        case .shareOther: "Shiriki kwa njia nyingine"
        case .yourCodes: "Misimbo yako"
        case .used: "Imetumika"
        case .expiresOn: "Inaisha %@"
        case .promoTerms: "Punguzo linatoka Zuri, kamwe si kutoka kwenye nauli ya dereva. Msimbo mmoja kwa safari."

        // Safety
        case .sosDuringTrip: "SOS wakati wa safari"
        case .sosDuringTripBody: "Bonyeza kitufe chekundu cha SOS kwenye safari yoyote inayoendelea kupiga 112 au kuwaarifu wasiliani wako na eneo lako la moja kwa moja."
        case .emergencyContacts: "Wasiliani wa dharura (%ld/3)"
        case .addContact: "Ongeza msiliani"
        case .maxContacts: "Unaweza kuongeza hadi wasiliani 3."
        case .contactNamePlaceholder: "mf. Mama"
        case .saveContact: "Hifadhi msiliani"
        case .autoShareTrips: "Shiriki safari zangu kiotomatiki"
        case .autoShareTripsBody: "Tuma kiungo cha safari kwa wasiliani wako kila dereva anapokubali."
        case .safetyTips: "Vidokezo vya usalama"
        case .safetyTip1: "Hakikisha namba ya gari kwenye programu inafanana na gari kabla ya kuingia."
        case .safetyTip2: "Muulize dereva jina lako — analiona kwenye programu yake."
        case .safetyTip3: "Shiriki safari yako na mtu unayemwamini."
        case .safetyTip4: "Simu kwa madereva zinapitia Zuri — namba yako inabaki siri."

        // Support
        case .chatWhatsApp: "Ongea WhatsApp"
        case .callSupport: "Piga msaada"
        case .supportHours: "Kila siku 06:00–23:00 · Majibu chini ya dakika 10"
        case .lastTrip: "Safari yako ya mwisho"
        case .faq: "Maswali ya kawaida"
        case .faqQ1: "Kamisheni sifuri inafanyaje kazi?"
        case .faqA1: "Madereva wanalipa ada ndogo ya kila wiki kutumia Zuri. Hatuchukui chochote kutoka kwenye nauli yako, hivyo dereva anabaki na 100%."
        case .faqQ2: "Nauli inakokotolewaje?"
        case .faqA2: "Msingi + umbali + muda, inapangwa wakati wa kuagiza ndani ya viwango vya LATRA. Hakuna bei ya kupanda ghafla."
        case .faqQ3: "Naweza kulipa kwa M-Pesa?"
        case .faqA3: "Ndiyo — M-Pesa, Mixx by Yas, Airtel Money na HaloPesa. Unganisha pochi chini ya Malipo. Taslimu inapatikana kila wakati."
        case .faqQ4: "Nikighairi je?"
        case .faqA4: "Bure ndani ya dakika 2 baada ya dereva kukubali. Baada ya hapo ada ndogo (TZS 500–1,000) inaenda kwa dereva. Kama dereva alikuomba ughairi, weka alama — hakuna ada."
        case .faqQ5: "Madereva pendwa wanafanyaje kazi?"
        case .faqA5: "Mpe dereva nyota 5 naye anaingia Madereva wangu. Akiwa mtandaoni unaweza kumuomba moja kwa moja na anaona ombi lako kwanza."
        case .faqQ6: "Zuri inapatikana nje ya Dar?"
        case .faqA6: "Bado. Bonyeza 'Nijulishe' kwenye eneo lolote lililo nje ya huduma na tutakuambia tutakapoanza hapo."
        case .legal: "Kisheria"
        case .termsOfService: "Masharti ya huduma"
        case .privacyPolicy: "Sera ya faragha"

        // Settings
        case .mapStyle: "Muonekano wa ramani"
        case .mapStyleBody: "Hubadilisha mwanga na rangi ya ramani. Majengo, maeneo na magari hubaki sawa."
        case .mapStyleMonochromeDay: "Kijivu cha mchana"
        case .mapStyleMonochromeDayBody: "Jiji la kijivu, mwanga wa mchana"
        case .mapStyleMonochromeDusk: "Kijivu cha jioni"
        case .mapStyleMonochromeDuskBody: "Jiji la kijivu, mwanga hafifu wa jioni"
        case .mapStyleNight: "Usiku"
        case .mapStyleNightBody: "Jiji la giza na taa za madirisha na barabara"
        case .mapStyleDawn: "Alfajiri"
        case .mapStyleDawnBody: "Mwanga wa joto wa asubuhi na vivuli virefu"
        case .mapStyleColourDay: "Rangi za mchana"
        case .mapStyleColourDayBody: "Bustani za kijani na maji ya bluu kwa rangi kamili"
        case .mapStyleFaded: "Rangi hafifu"
        case .mapStyleFadedBody: "Rangi laini inayoweka majina mbele"
        case .language: "Lugha"
        case .notifications: "Arifa"
        case .tripUpdates: "Taarifa za safari"
        case .promoUpdates: "Ofa na punguzo"
        case .account: "Akaunti"
        case .logOut: "Toka"
        case .logOutConfirmTitle: "Utoke kwenye Zuri?"
        case .deleteAccount: "Futa akaunti"
        case .deleteAccountSubtitle: "Inaondoa data yako kwenye kifaa hiki"
        case .deleteAccountConfirmTitle: "Ufute akaunti yako?"
        case .deleteAccountConfirmBody: "Wasifu wako, sehemu zilizohifadhiwa, madereva pendwa na historia ya safari vitaondolewa. Hili haliwezi kutenduliwa."
        case .deleteAccountConfirm: "Futa kila kitu"

        case .siriGuide: "Siri, Shortcuts na wijeti"
        case .siriGuideSubtitle: "Agiza na fuatilia safari bila kufungua programu"
        case .siriGuideIntro: "Zuri inafanya kazi na Siri, programu ya Shortcuts na skrini yako ya nyumbani. Haya ndiyo yote unayoweza kufanya na maneno ya kusema. Sema maneno kwa Kiingereza — Siri haielewi Kiswahili bado."
        case .siriGuideBookTitle: "Agiza kwa sauti"
        case .siriGuideBookBody: "Uliza bei kwanza, au omba gari moja kwa moja. Siri hukumbuka jibu, hivyo unaweza kusema \"agiza ya comfort\" baada ya kupata bei. Nyumbani na Kazini zinaeleweka kama sehemu."
        case .siriGuideBookPhrase1: "Bei ya safari kwenda uwanja wa ndege Zuri"
        case .siriGuideBookPhrase2: "Nipe gari kwenda kazini Zuri"
        case .siriGuideBookPhrase3: "Rudia safari yangu ya Zuri"
        case .siriGuideRideTitle: "Wakati wa safari"
        case .siriGuideRideBody: "Dereva akiwa njiani au ukiwa ndani ya gari, Siri inaweza kusoma muda wa kufika, gari na namba ya kutafuta na nambari yako ya kuanza, kughairi (inakuambia ada kwanza), au kubadilisha unakoenda."
        case .siriGuideRidePhrase1: "Dereva wangu wa Zuri yuko wapi?"
        case .siriGuideRidePhrase2: "Ghairi safari yangu ya Zuri"
        case .siriGuideRidePhrase3: "Badilisha ninakoenda kuwa Slipway"
        case .siriGuideScreenTitle: "Zungumzia kilicho kwenye skrini"
        case .siriGuideScreenBody: "Kwenye iOS 27, Siri inaona kile Zuri inaonyesha, hivyo unaweza kusema \"hii\", \"yeye\" au \"hapa\" badala ya kurudia maelezo. Kila kitendo hapa chini pia kinafanya kazi kwa jina kwenye iOS za zamani."
        case .siriGuideScreen1: "Chaguo za safari"
        case .siriGuideScreen1Body: "\"Agiza ya bei nafuu\" · \"Bajaji inachukua muda gani?\" · \"Ongeza kituo Kariakoo\""
        case .siriGuideScreen2: "Dereva njiani"
        case .siriGuideScreen2Body: "\"Mpigie simu\" · \"Mtumie Amina safari yangu\" · \"Namba ya gari ni ipi?\" · \"Mwongeze dereva huyu kwa madereva wangu\""
        case .siriGuideScreen3: "Safari imeisha au risiti"
        case .siriGuideScreen3Body: "\"Mpe bakshishi ya shilingi 1,000\" · \"Ipe safari hii nyota tano\" · \"Shiriki risiti hii\" · \"Rudia safari hii\""
        case .siriGuideScreen4: "Sehemu kwenye utafutaji au za karibuni"
        case .siriGuideScreen4Body: "\"Hifadhi hii kama Kazini\" · \"Mtumie Juma anwani hii\" · \"Nipeleke hapa\""
        case .siriGuideScreen5: "Madereva wangu"
        case .siriGuideScreen5Body: "\"Omba Neema\" · \"Niambie Hassan akiwa mtandaoni\""
        case .siriGuideShortcutsTitle: "Tengeneza zako kwenye Shortcuts"
        case .siriGuideShortcutsBody: "Kila kitendo hapo juu ni kipande kwenye programu ya Shortcuts: Tafuta Sehemu, Pata Bei, Omba Safari, Angalia Safari Yangu, Ghairi, Badilisha Unakoenda, Safiri Tena, Hifadhi Sehemu, Ongeza Kituo, Pata Risiti na vitendo vya madereva. Viunganishe, viweke kwenye Action Button au Control Centre, au viendeshe kwa ratiba — kwa mfano bei ya kwenda kazini kila siku ya kazi saa 1:30 asubuhi."
        case .siriGuideOpenShortcuts: "Fungua Shortcuts"
        case .siriGuideWidgetTitle: "Wijeti ya skrini ya nyumbani"
        case .siriGuideWidgetBody: "Ukubwa nne. Ndogo na wastani zinaonyesha safari inayoendelea, au muda wa kuchukuliwa kwa Gari, Bajaji na Boda kando ya kitufe cha kutafuta, Nyumbani na Kazini. Kubwa inaonyesha ukurasa wa nyumbani. Kwenye iOS 27 ukubwa wa urefu kamili unaongeza madereva wako, za karibuni, pochi na safari zilizopita; kila mstari unafungua skrini husika. Wijeti hujaa baada ya kufungua Zuri mara moja."
        case .siriGuideWidgetStep1: "Gusa na ushikilie sehemu tupu kwenye skrini ya nyumbani"
        case .siriGuideWidgetStep2: "Gusa Edit, kisha Add Widget, na utafute Zuri"
        case .siriGuideWidgetStep3: "Chagua ukubwa na ugusa Add Widget"
        case .siriGuideAvailability: "Maneno ya sauti na wijeti vinafanya kazi kwenye iOS 18 na baadaye. Uelewa wa skrini na wijeti ya urefu kamili vinahitaji iOS 27."
        case .siriGuideTryIt: "Jaribu sasa"

        // Mobile money, ID verification, billboards
        case .topUpChooseWallet: "Chagua pochi"
        case .topUpEnterAmount: "Weka kiasi"
        case .topUpAddFrom: "Weka %@ kutoka %@"
        case .topUpNewBalance: "Salio jipya %@"
        case .topUpMinimumHint: "Kiwango cha chini %@"
        case .notLinked: "Haijaunganishwa"
        case .linkShort: "Unganisha"
        case .linked: "Imeunganishwa"
        case .linkWithNumber: "Unganisha %@"
        case .useAnotherNumber: "Tumia namba nyingine"
        case .autoTopUp: "Kujaza pochi kiotomatiki"
        case .autoTopUpOff: "Imezimwa"
        case .autoTopUpSummary: "Chini ya %@, weka %@ kutoka %@"
        case .autoTopUpTitle: "Kujaza kiotomatiki"
        case .autoTopUpBody: "Salio likipungua, Zuri inatuma ombi moja la PIN kwenye simu yako kuongeza pesa. Hakuna pesa inayotoka mpaka uidhinishe."
        case .autoTopUpThreshold: "Salio likishuka chini ya"
        case .autoTopUpAmount: "Weka kiasi hiki"
        case .autoTopUpFrom: "Kutoka"
        case .autoTopUpSave: "Hifadhi"
        case .autoTopUpNeedsWallet: "Unganisha pochi ya pesa ya simu kwanza."
        case .autoTopUpInvalid: "Kiasi lazima kiwe angalau TZS 1,000."
        case .autoTopUpDone: "Kujaza kiotomatiki: %@ imewekwa"
        case .walletAutoTopUpTitle: "Kujaza kiotomatiki kutoka %@"
        case .mmWaitingRow: "Inasubiri idhini"
        case .mmCheckPhoneTitle: "Angalia simu yako"
        case .mmCheckPhoneBody: "Idhinisha %@ kwenye ombi la PIN la %@. Huhitaji kufungua programu yoyote."
        case .mmRidePromptBody: "Idhinisha %@ kwenye ombi la PIN la %@ kulipia safari hii."
        case .mmExpiresIn: "Ombi linaisha baada ya %@"
        case .mmKeepOpen: "Unaweza kuacha skrini hii wazi au kuondoka. Tutasasisha pochi yako vyovyote."
        case .mmTestMode: "Hali ya majaribio"
        case .mmTestModeBody: "Hakuna pesa halisi inayotoka. Hivi ndivyo %@ itakavyoonyesha kwenye simu yako malipo yakianza rasmi."
        case .mmPromptText: "Lipa %@ kwa ZURI?\nWeka PIN kuthibitisha"
        case .mmPromptPin: "PIN"
        case .mmPromptSend: "Tuma"
        case .mmPromptCancel: "Ghairi"
        case .mmPromptHint: "Tarakimu 4 zozote zinaidhinisha. 0000 inajaribu PIN isiyo sahihi."
        case .mmSimulateInsufficient: "Jaribio: pesa haitoshi"
        case .mmApprovedTitle: "%@ imewekwa"
        case .mmApprovedBody: "Salio jipya %@"
        case .mmReference: "Kumbukumbu"
        case .mmDone: "Imekamilika"
        case .mmChangeAmount: "Badilisha kiasi"
        case .mmFailDeclined: "Malipo yameghairiwa"
        case .mmFailDeclinedBody: "Ombi liliaghairiwa kwenye simu yako. Hakuna pesa iliyotoka."
        case .mmFailWrongPin: "PIN si sahihi"
        case .mmFailWrongPinBody: "PIN haikulingana. Hakuna pesa iliyotoka."
        case .mmFailTimeout: "Ombi limeisha muda"
        case .mmFailTimeoutBody: "Hatukupata idhini yako kwa wakati. Hakuna pesa iliyotoka."
        case .mmFailFunds: "Pesa haitoshi"
        case .mmFailFundsBody: "Salio lako la %@ ni dogo kwa kiasi hiki."
        case .mmFailOther: "Malipo hayakufanikiwa"
        case .mmFailOtherBody: "Hakuna pesa iliyotoka. Jaribu tena baada ya muda mfupi."
        case .mmStartFailed: "Imeshindwa kufikia huduma ya malipo. Angalia mtandao wako kisha ujaribu tena."
        case .idVerify: "Thibitisha kwa kitambulisho"
        case .idVerified: "Kitambulisho kimethibitishwa"
        case .idVerifySubtitle: "Skani kitambulisho au pasipoti yoyote kujaza taarifa zako"
        case .idPrimerTitle: "Thibitisha kwa kitambulisho chako"
        case .idPrimerSubtitle: "Skani kitambulisho cha NIDA, leseni ya udereva au pasipoti yoyote. Tunajaza taarifa zako kwa ajili yako."
        case .idPrimerBullet1: "Inafanya kazi na vitambulisho vya NIDA, leseni za udereva na pasipoti za nchi yoyote."
        case .idPrimerBullet2: "Inasomwa kwenye simu yako. Picha ya kitambulisho chako haipakiwi wala haihifadhiwi."
        case .idPrimerBullet3: "Madereva wanaona alama ya uthibitisho tu, si taarifa za kitambulisho chako."
        case .idScanAction: "Skani kitambulisho changu"
        case .idSkip: "Ruka kwa sasa"
        case .idScanTitle: "Skani kitambulisho chako"
        case .idScanHintPassport: "Kwa pasipoti, onyesha ukurasa wa picha wenye mistari miwili chini."
        case .idScanHintAlign: "Onyesha kitambulisho chako kwa kamera. Pembe yoyote inafaa."
        case .idScanHintSteady: "Kimepatikana. Shikilia bila kutikisa…"
        case .idScanHintCloser: "Sogeza karibu kidogo"
        case .idScanHintGlare: "Inamisha kadi kidogo kuepuka mwangaza"
        case .idScanHintReading: "Tunasoma taarifa zako…"
        case .idScanCaptured: "Tayari"
        case .idCameraDeniedTitle: "Kamera imezimwa"
        case .idCameraDeniedBody: "Ruhusu kamera kwenye Mipangilio ili kuskani kitambulisho chako."
        case .idNoCameraTitle: "Hakuna kamera"
        case .idNoCameraBody: "Uthibitisho wa kitambulisho unahitaji kamera. Jaribu tena kwenye simu yenye kamera."
        case .idOpenSettings: "Fungua Mipangilio"
        case .idReviewTitle: "Hakiki taarifa zako"
        case .idReviewSubtitle: "Taarifa zote hapa chini zimesomwa kutoka kitambulisho chako kwenye simu yako. Kama kuna kosa, skani tena."
        case .idChecksumOK: "Mistari ya mashine imethibitishwa"
        case .idGivenNames: "Jina la kwanza na la kati"
        case .idSurname: "Jina la ukoo"
        case .idDocumentNumber: "Namba ya kitambulisho au pasipoti"
        case .idNationality: "Uraia"
        case .idSex: "Jinsi"
        case .idSexFemale: "Mwanamke"
        case .idSexMale: "Mwanaume"
        case .idSexUnspecified: "Haijatajwa"
        case .idDateOfBirth: "Tarehe ya kuzaliwa"
        case .idExpiry: "Tarehe ya kuisha"
        case .idCheckField: "Hakiki hapa: hatukuweza kusoma vizuri"
        case .idUseCardPhoto: "Tumia picha ya kadi kama picha yangu ya wasifu"
        case .idUseName: "Tumia jina hili kwenye wasifu wangu"
        case .idConfirm: "Thibitisha taarifa"
        case .idRescan: "Skani tena"
        case .idMissingError: "Hatukuweza kusoma jina, namba ya kitambulisho na tarehe ya kuzaliwa vizuri. Skani tena kwenye mwanga mzuri."
        case .idUnderageError: "Unahitaji kuwa na miaka 18 au zaidi kuthibitisha na Zuri."
        case .idExpiredError: "Kitambulisho hiki kimeisha muda. Skani kitambulisho halali."
        case .idSaved: "Kitambulisho kimethibitishwa"
        case .idKindNida: "Kitambulisho cha NIDA"
        case .idKindPassport: "Pasipoti"
        case .idKindNationalID: "Kitambulisho cha taifa"
        case .idKindDriving: "Leseni ya udereva"
        case .idKindResidence: "Kibali cha ukaazi"
        case .idKindOther: "Hati ya utambulisho"
        case .idDocumentType: "Hati"
        case .idStatusBody: "Imethibitishwa tarehe %@ kwa %@ yako."
        case .idRemove: "Ondoa uthibitisho"
        case .adSponsored: "Tangazo"
        case .adTestBadge: "Tangazo la majaribio"
        case .adKfcHeadline: "Vipande 2 + chipsi"
        case .adKfcOffer: "TZS 7,000 kwenye tawi lolote la Dar es Salaam. Fika huko na Zuri."
        case .adNearestBranch: "Tawi la karibu: %@"
        case .adRideThere: "Safiri hadi %@"
        case .adDisclaimer: "Tangazo la mfano kwa maonyesho kwa watangazaji."
        case .walletEnterCode: "Weka namba ya uthibitisho"
        case .walletCodeSentTo: "Tumetuma namba ya tarakimu 6 kwa SMS kwenda %@."
        case .walletTestCode: "Hali ya majaribio, SMS bado haijaunganishwa. Namba yako ni %@"
        case .walletDetectedAs: "Hii ni namba ya %@"
        case .walletDetectedName: "Imesajiliwa kwa %@"
        case .walletWrongNetwork: "Namba hii iko %@, si %@."
        case .walletSwitchTo: "Unganisha kama %@ badala yake"
        case .walletUnknownNetwork: "Hatukutambua mtandao huu. Hakiki namba."
        case .walletSendCode: "Tuma namba"
        case .walletResendCode: "Tuma tena"
        case .walletResendIn: "Tuma tena baada ya %@"
        case .walletEditNumber: "Badilisha namba"
        case .walletVerifiedToast: "%@ imeunganishwa na kuthibitishwa"
        case .walletNeedsVerify: "Thibitisha kwa SMS"
        case .walletOwnershipNote: "Tunatuma namba kwa SMS kuthibitisha kuwa namba ni yako. Bado utaidhinisha kila malipo kwa PIN yako."
        case .changeWalletNumber: "Tumia namba nyingine"
        case .topUpStep1: "Chagua pochi"
        case .topUpStep2: "Andika kiasi"
        case .topUpStep3: "Weka PIN ya %@ kwenye simu"
        case .changeNumberTitle: "Badilisha namba ya %@"
        case .currentNumber: "Namba iliyounganishwa: %@"
        case .unlinkWallet: "Ondoa pochi hii"
        case .signInTitle: "Karibu Zuri"
        case .signInSubtitle: "Ingia ili safari, pochi na maeneo yako yahifadhiwe salama kwenye akaunti yako."
        case .signInGoogle: "Endelea na Google"
        case .signInPhoneInstead: "Namba yako ya simu itaongezwa baadaye, kwa madereva na pesa za simu."
        case .signInTerms: "Kwa kuendelea unakubali Masharti na Sera ya Faragha ya Zuri."
        case .signInFailed: "Kuingia hakukukamilika. Tafadhali jaribu tena."
        case .signedInAs: "Umeingia kama %@"
        case .signOutGoogle: "Toka"
        case .accountSynced: "Akaunti imehifadhiwa salama"
        case .yourRideNow: "Gari lako sasa"
        case .routeUpdated: "Njia imesasishwa, dereva amejulishwa"
        case .changingThisStop: "Tafuta mahali papya…"
        case .tapToChange: "Gusa kubadilisha"
        case .changeRoute: "Badilisha njia"
        case .planYourTrip: "Panga safari yako"
        case .searchPickup: "Tafuta mahali pa kuchukuliwa"
        case .newFare: "Nauli mpya"
        case .updateRoute: "Sasisha njia"
        case .findingAddress: "Inatafuta anwani…"
        case .chatWithDriver: "Ongea na dereva"
        case .chatAutoTranslate: "Ujumbe unatafsiriwa moja kwa moja"
        case .chatEmpty: "Mjulishe dereva kuwa unatoka. Ujumbe unatafsiriwa kati ya Kiswahili na Kiingereza."
        case .chatQuickComing: "Natoka sasa hivi"
        case .chatQuickHere: "Niko mahali pa kuchukuliwa"
        case .chatQuickFiveMin: "Nipe dakika 5"
        case .chatQuickWhere: "Uko wapi?"
        case .chatPlaceholder: "Ujumbe"
        case .chatSend: "Tuma"
        case .chatTranslated: "Imetafsiriwa"
        }
    }
}
